(define (problem gripper-2) 
(:domain gripper-domain) 
(:objects rooma roomb roomc roomd ball1 ball2 ball3 ball4 ball5 left)
(:init 
(room rooma) 
(room roomb) 
(room roomc)
(room roomd)
(ball ball1) 
(ball ball2)
(ball ball3)
(ball ball4)
(ball ball5)
(gripper left) 
(at-robby rooma) 
(free left)
(at ball1 rooma) 
(at ball2 rooma)
(at ball3 roomb)
(at ball4 roomc)
(at ball5 roomc)
)
 (:goal (and (at ball2 roomc) (at ball5 rooma) (at ball4 roomb))))