(define (problem gripper-3) 
(:domain gripper-domain) 
(:objects rooma roomb roomc roomd roome roomf ball1 ball2 ball3 ball4 ball5 ball6 ball7 ball8 up)
(:init 
(room rooma) 
(room roomb) 
(room roomc)
(room roomd)
(room roome)
(room roomf)
(ball ball1) 
(ball ball2)
(ball ball3)
(ball ball4)
(ball ball5)
(ball ball6)
(ball ball7)
(ball ball8)
(gripper up) 
(at-robby roomc)
(free up)
(at ball1 rooma) 
(at ball2 rooma)
(at ball3 roomb)
(at ball4 roomc)
(at ball5 roomc)
(at ball6 roomf)
(at ball7 rooma)
(at ball8 roomc)
)
 (:goal (and (at ball2 roomc) (at ball5 rooma) (at ball4 roomb) (at ball1 roomf) (at ball3 rooma) (at ball6 roomc) (at ball7 roomc) (at ball8 roome))))